﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿/**
 * Application Configuration
 * All sensitive settings should come from environment variables
 */
// API Configuration
export const API_CONFIG = {
  BASE_URL: '/api',
  TIMEOUT: 10000
};
// Role Constants
export const ROLES = {
  CEO: 'CEO',
  STORE_KEEPER: 'STORE_KEEPER',
  GENERAL_MANAGER: 'GENERAL_MANAGER',
  CA: 'CA',
  SALES: 'SALES_MANAGER',
  SITE_INCHARGE: 'SITE_INCHARGE',
  SITE_ENGINEER: 'SITE_ENGINEER',
  EXECUTIVE: 'EXECUTIVE'
} as const;
// Role Display Labels
export const ROLE_LABELS: Record<string, string> = {
  [ROLES.CEO]: 'CEO',
  [ROLES.STORE_KEEPER]: 'Store Keeper',
  [ROLES.GENERAL_MANAGER]: 'General Manager',
  [ROLES.CA]: 'CA',
  [ROLES.SALES]: 'Sales Manager',
  [ROLES.SITE_INCHARGE]: 'Site Incharge',
  [ROLES.SITE_ENGINEER]: 'Site Engineer',
  [ROLES.EXECUTIVE]: 'Executive'
};
// Admin Configuration (from environment variables)
export const ADMIN_CONFIG = {
  ROOT_CEO_EMAIL: import.meta.env.VITE_ROOT_CEO_EMAIL || '',
  INITIAL_ADMIN_EMAIL: import.meta.env.VITE_INITIAL_ADMIN_EMAIL || '',
};
// Role-based access configuration
export const ROLE_PERMISSIONS = {
  [ROLES.CEO]: {
    canViewDashboard: true,
    canManageUsers: true,
    canManageMasters: true,
    canCreateMasters: true,
    canDeleteMasters: true,
    canEditMastersAdmin: true,
    canManageProjects: true,
    canCreateProjects: true,
    canEditProjectStatus: true,
    canManageApprovals: true,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: true,
    canDeleteApprovals: true,
    canManageInventory: true,
    canEditInventoryAdmin: true,
    canViewCustomers: true,
    canCreateCustomerPayments: true,
    canManageGrn: true,
    canManageContractorPayments: true,
    canCreateContractorPayments: true,
    canDeletePayments: true,
    canViewReports: true,
    canManageProcurement: true,
    canRaisePR: true,
    canApprovePR: true,
    canCreatePO: true,
    canOverrideProcurement: true,
  },
  [ROLES.CA]: {
    canViewDashboard: true,
    canManageUsers: false,
    canManageMasters: true,
    canViewMasters: true,
    canCreateMasters: true,
    canDeleteMasters: false,
    canEditMastersAdmin: true,
    canManageProjects: true,
    canViewProjects: true,
    canCreateProjects: true,
    canEditProjectStatus: true,
    canManageApprovals: true,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: true,
    canDeleteApprovals: false,
    canManageInventory: false,
    canViewInventory: true,
    canEditInventoryAdmin: false,
    canViewCustomers: true,
    canCreateCustomerPayments: true,
    canManageGrn: false,
    canViewGrn: true,
    canManageContractorPayments: true,
    canViewContractorPayments: true,
    canCreateContractorPayments: true,
    canDeletePayments: false,
    canViewReports: true,
    canManageProcurement: true,
    canViewProcurement: true,
    canRaisePR: false,
    canApprovePR: true,
    canCreatePO: false,
    canOverrideProcurement: true,
  },
  [ROLES.GENERAL_MANAGER]: {
    canViewDashboard: true,
    canViewExecutiveDashboard: true,
    canManageUsers: false,
    canManageMasters: true,
    canViewMasters: true,
    canCreateMasters: true,
    canDeleteMasters: false,
    canEditMastersAdmin: false,
    canManageProjects: true,
    canCreateProjects: true,
    canEditProjectStatus: false,
    canManageApprovals: false,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: false,
    canDeleteApprovals: false,
    canManageInventory: true,
    canEditInventoryAdmin: false,
    canViewCustomers: true,
    canCreateCustomerPayments: true,
    canManageGrn: true,
    canManageContractorPayments: true,
    canCreateContractorPayments: true,
    canDeletePayments: false,
    canViewReports: true,
    canManageProcurement: true,
    canRaisePR: false,
    canApprovePR: false,
    canCreatePO: false,
    canOverrideProcurement: false,
  },
  [ROLES.SALES]: {
    canViewDashboard: true,
    canManageUsers: false,
    canManageMasters: false,
    canCreateMasters: false,
    canDeleteMasters: false,
    canEditMastersAdmin: false,
    canManageProjects: false,
    canCreateProjects: false,
    canEditProjectStatus: false,
    canManageApprovals: false,
    canViewApprovals: false,
    canRaiseApprovals: false,
    canApproveRequests: false,
    canDeleteApprovals: false,
    canManageInventory: false,
    canViewInventory: true,
    canEditInventoryAdmin: false,
    canViewCustomers: true,
    canCreateCustomerPayments: true,
    canManageGrn: false,
    canViewGrn: true,
    canManageContractorPayments: false,
    canViewContractorPayments: true,
    canCreateContractorPayments: false,
    canDeletePayments: false,
    canViewReports: true,
    canManageProcurement: false,
    canViewProcurement: true,
    canRaisePR: false,
    canApprovePR: false,
    canCreatePO: false,
    canOverrideProcurement: false,
  },
  [ROLES.STORE_KEEPER]: {
    canViewDashboard: true,
    canManageUsers: false,
    canManageMasters: false,
    canViewMasters: true,
    canCreateMasters: false,
    canDeleteMasters: false,
    canEditMastersAdmin: false,
    canManageProjects: false,
    canViewProjects: true,
    canCreateProjects: false,
    canEditProjectStatus: false,
    canManageApprovals: true,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: false,
    canDeleteApprovals: false,
    canManageInventory: true,
    canViewInventory: true,
    canEditInventoryAdmin: true,
    canViewCustomers: true,
    canCreateCustomerPayments: false,
    canManageGrn: true,
    canViewGrn: true,
    canManageContractorPayments: false,
    canViewContractorPayments: true,
    canCreateContractorPayments: false,
    canDeletePayments: false,
    canViewReports: true,
    canManageProcurement: true,
    canViewProcurement: true,
    canRaisePR: true,
    canApprovePR: false,
    canCreatePO: false,
    canOverrideProcurement: false,
  },
  [ROLES.SITE_INCHARGE]: {
    canViewDashboard: false,
    canManageUsers: false,
    canManageMasters: false,
    canCreateMasters: false,
    canDeleteMasters: false,
    canEditMastersAdmin: false,
    canManageProjects: false,
    canCreateProjects: false,
    canEditProjectStatus: false,
    canManageApprovals: true,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: false,
    canDeleteApprovals: false,
    canManageInventory: true,
    canEditInventoryAdmin: true,
    canViewCustomers: false,
    canCreateCustomerPayments: false,
    canManageGrn: true,
    canManageContractorPayments: false,
    canCreateContractorPayments: false,
    canDeletePayments: false,
    canViewReports: false,
    canManageProcurement: true,
    canRaisePR: true,
    canApprovePR: false,
    canCreatePO: false,
    canOverrideProcurement: false,
  },
  [ROLES.EXECUTIVE]: {
    canViewDashboard: true,
    canManageUsers: false,
    canManageMasters: false,
    canViewMasters: true,
    canCreateMasters: false,
    canDeleteMasters: false,
    canEditMastersAdmin: false,
    canManageProjects: false,
    canViewProjects: true,
    canCreateProjects: false,
    canEditProjectStatus: false,
    canManageApprovals: false,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: false,
    canDeleteApprovals: false,
    canManageInventory: false,
    canViewInventory: true,
    canEditInventoryAdmin: false,
    canViewCustomers: true,
    canCreateCustomerPayments: false,
    canManageGrn: false,
    canViewGrn: true,
    canManageContractorPayments: false,
    canViewContractorPayments: true,
    canCreateContractorPayments: false,
    canDeletePayments: false,
    canViewReports: true,
    canManageProcurement: false,
    canViewProcurement: true,
    canRaisePR: false,
    canApprovePR: false,
    canCreatePO: false,
    canOverrideProcurement: false,
  },
  [ROLES.SITE_ENGINEER]: {
    // Cloned from SITE_INCHARGE â€” separate immutable identity, permissions may diverge later
    canViewDashboard: false,
    canManageUsers: false,
    canManageMasters: false,
    canCreateMasters: false,
    canDeleteMasters: false,
    canEditMastersAdmin: false,
    canManageProjects: false,
    canCreateProjects: false,
    canEditProjectStatus: false,
    canManageApprovals: true,
    canViewApprovals: true,
    canRaiseApprovals: true,
    canApproveRequests: false,
    canDeleteApprovals: false,
    canManageInventory: true,
    canEditInventoryAdmin: true,
    canViewCustomers: false,
    canCreateCustomerPayments: false,
    canManageGrn: true,
    canManageContractorPayments: false,
    canCreateContractorPayments: false,
    canDeletePayments: false,
    canViewReports: false,
    canManageProcurement: true,
    canRaisePR: true,
    canApprovePR: false,
    canCreatePO: false,
    canOverrideProcurement: false,
  },
} as const;
// Validation constraints
export const VALIDATION_RULES = {
  PASSWORD_MIN_LENGTH: 8,
  PROJECT_CODE_PATTERN: /^[A-Z0-9\-]+$/,
  PLOT_NUMBER_PATTERN: /^[A-Z0-9\-]+$/,
};
// Default values (safe, non-sensitive)
export const DEFAULTS = {
  INVENTORY_POLL_INTERVAL: 5000, // ms
  PAGINATION_SIZE: 20,
  DATE_FORMAT: 'YYYY-MM-DD',
};
